version: 2

models:
    - name: customers
      description: "A starter dbt model"
      columns:
          - name: customer_id
          - name: first_name
          - name: last_name
          - name: first_order
          - name: most_recent_order
          - name: number_of_orders
          - name: customer_lifetime_value
      database: PC_HEVODATA_DB
      schema: PUBLIC
      materialized: table